### ISSUE TITLE
已同步的"用户→文稿"重的文件夹被识别为非iCloud环境

### ISSUE THREAD

**Issue by fishiu** [HaoChuan9421/nosync-icloud#10]
虽然不影响使用，但是或许可以改进，我猜是通过pwd来检测是不是在iCloud里面？
桌面没试过，我猜一样。

**Comment by haochuan9421** [comment]
是的，是通过路径是否包含`com~apple~CloudDocs`来判断的，我的电脑没开“同步桌面和文稿到iCloud”，如果你的开了可以测试一下，我印象如果电脑激活的时候选择打开了“同步桌面和文稿到iCloud”，他们的路径也是会变的。如果不是的话，暂时就不知道有啥办法可以检测了。

**Comment by fishiu** [comment]
路径没有变（准确的说是两种路径都可以访问到，但是macos默认非iCloud路径）
  
​

**Comment by haochuan9421** [comment]
那好吧🤷‍♂️，那只能在提示“是否继续？”的时候多回车一下了，如果你知道有啥检测的方法，也可以提一个PR

**Comment by haochuan9421** [comment]
如果像你说的那样，两个路径都可以访问的话，当判断路径包含桌面或文稿时，也可以尝试应Node的fs模块去检测一下对应的iCloud路径，看存在不，如果存在就跳过询问。

**Comment by fishiu** [comment]
有道理！这就很好办了哈哈哈哈
  
​

**Comment by haochuan9421** [comment]
可以了，安装一下新版的就行了

**Comment by fishiu** [comment]
nice👍
