### ISSUE TITLE
How do you deal with .git, .next, .sst, .open-next folders?

### ISSUE THREAD

**Issue by martg0** [HaoChuan9421/nosync-icloud#16]
Hi! how do you deal with .git, .next, .sst, .open-next folders? Could we follow the same approach?
.git folder is huge, and doesn't make sense to sync

**Comment by haochuan9421** [comment]
This might be what you want.
<img width="1099" alt="image" src="https://github.com/haochuan9421/nosync-icloud/assets/5093611/ddf89d33-1be8-4b68-a571-aff073bb0fad">

**Comment by haochuan9421** [comment]
But pay attention that some folders may not work properly after using symbolic link.

**Comment by martg0** [comment]
謝謝 @haochuan9421 !!
